name: Setup Server

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: self-hosted

    steps:
      # - name: Git Clone
      #   uses: actions/checkout@v7

      # - name: Install Nodejs
      #   uses: actions/setup-node@v7
      #   with:
      #     node-version: "24.x"

      # - name: Install Packages
      #   run: npm install

      - name: Present working directory
        run: pwd

      # - name: create file and enter text
      #   run: |
      #     touch hello.txt
      #     echo "from the github action workflow" > hello.txt

      # - name: Install nginx
      #   run: |
      #     cd ~
      #     sudo apt update >/dev/null
      #     sudo apt upgrade -y >/dev/null
      #     sudo apt install nginx -y

      - name: login to private-server
        run: |
          cd ~
          ssh -i .ssh/github_actions_ec2 ${{secrets.HOST_NAME}}@${{secrets.HOST_ADDRESS}}
          # sudo apt update
          # sudo apt upgrade -y
          sudo -i 
          whoami
          pwd
          hostname
          apt list --upgradable
